version: '3.7'

services:
  graphql.webapi:
    image: graphqlwebapi
    build:
      context: .
      dockerfile: GraphQL.Webapi/Dockerfile
    ports:
      - 8081:80
    networks:
      - graphql-network

networks:
  graphql-network: